### PR TITLE
Update commodity.py

### PR DESCRIPTION
**Pull request by gorf**
to solve the bug I encounted below, I change the function one() to first()
[Commodity<SS:600016.SS>]
prices: {'600016.SS': '6.340'}
600016.SS :  6.340
--> modifying existing price  Price<2018-09-28 : 6.34 CNY/600016.SS>
[Commodity<SS:600016.SS>]
Traceback (most recent call last):
  File "./get_online_stock_prices.py", line 196, in <module>
    acquire_online_prices(DATABASE_PATH)
  File "./get_online_stock_prices.py", line 180, in acquire_online_prices
    book.save()
  File "/home/lq/.local/lib64/python3.6/site-packages/piecash-0.18.0-py3.6.egg/piecash/core/book.py", line 270, in save
    self.session.commit()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 436, in _prepare_impl
    self.session.dispatch.before_commit(self.session)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/event/attr.py", line 246, in __call__
    fn(*args, **kw)
  File "/home/lq/.local/lib64/python3.6/site-packages/piecash-0.18.0-py3.6.egg/piecash/core/book.py", line 214, in validate_book
    tx.validate()
  File "/home/lq/.local/lib64/python3.6/site-packages/piecash-0.18.0-py3.6.egg/piecash/core/commodity.py", line 97, in validate
    date=self.date).one()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 2890, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

### CODE REVIEW

**Comment by gorf** [comment]
OK, I'll try it.

**Comment by gorf** [comment]
> Tx @gorf, should I understand that with this patch it works for you?

It works for me. I have tried to use "one()", with source=self.source, but still have the bug.

**Comment by sdementen** [comment]
hi @gorf 
could we reexplore this issue (or close the MR) ?
if you can reproduce the bug on piecash 1.1 with a gnucash book created by piecash, that would be the easiest

**Comment by sdementen** [comment]
I close it for now, feel free to reopen if needed

**Pull request closed without merging**
