### PR TITLE
Fix python version bindings per setuptools docs

### PR DESCRIPTION
**Pull request by techalchemy**
- Fix python-specific dependency installation to use install_requires
rather than extras_requires per [setuptools
documentation](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies)

### CODE REVIEW

**Comment by sdementen** [comment]
tx @techalchemy ! however the pandas is an option/extra (maybe tricky to name it as a real python package...).
What I want is for the user to be able to do a "pip install piecash" or a "pip install piecash[pandas]" if he/she wants the "pandas optional features of piecash" to be enabled. And for this "pandas" option, I want to have a conditional dependency on the python version (as pandas==0.22.0 has no more wheels for py34).

**Comment by sdementen** [comment]
And can I have in the extras_require for my test section something like
        'test': ['pytest', 'pytest-cov', 'tox',
                 'piecash[pandas,finance-quote,mysql,postgres]'],
(ie self refering to my own package with the different options/extras I want for my test) ?
Or is it really wrong and I should build my list of dependencies before hand ?

**Comment by sdementen** [comment]
@techalchemy For my first question, I tried also:
```
extras_require={
    'postgres': ["psycopg2"],
    'mysql': ["PyMySQL"],
    'pandas': ['pandas==0.21.0;python_version=="3.4"', # no wheels for py34 beyond 0.21.0
               'pandas;python_version!="3.4"'],
```
but it complains with
```
error in piecash setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.            
```

**Comment by techalchemy** [comment]
You can't refer to your own package in your `setup.py`, because doing so suggests that your own package needs to be installed during the installation process for your package.  This is an infinite recursion, it is implicit in the installation of your package that your package is installed

will update the pr though

**Comment by sdementen** [comment]
My use case is that, for the tests, I want the extras (of the package) to be installed too. And I want to avoid repeating the list of packages of each option in the extras_require["test"]. Any alternative?

**Comment by techalchemy** [comment]
With this approach you can now use just the `tests` extra

**Comment by sdementen** [comment]
integrated changes in another branch, closing this one. tx @techalchemy for your support!

**Comment by techalchemy** [comment]
sure thing

**Pull request closed without merging**
