### PR TITLE
Support the GC 2.7.2 schema

### PR DESCRIPTION
**Pull request by MisterY**
Update the supported version of Prices table.
The date field has been expanded with no changes in data. Updating the supported version number.

### CODE REVIEW

**Comment by MisterY** [comment]
Resolves #49.

**Comment by sdementen** [comment]
I see in the source code https://github.com/Gnucash/gnucash/blame/0026b108517a4f9c3f65d2d8e595b4b5d28d07ff/libgnucash/backend/sql/gnc-sql-column-table-entry.cpp#L373 while before it was https://github.com/Gnucash/gnucash/blame/db719191a1319d5ef00e1337f4aa43013fff2645/src/backend/sql/gnc-sql-column-table-entry.cpp#L400

Aren't all tables with date changed in the same way ?

**Comment by MisterY** [comment]
What are the other effects of this change? I see no change in stored data.

**Comment by sdementen** [comment]
commit in gnucash linked to it https://github.com/Gnucash/gnucash/commit/10b006fdc1fe67c6caff7efca163406c89e78187

**Comment by MisterY** [comment]
Solved #51.
All table changes analyzed and updated.

**Comment by MisterY** [comment]
ok, so we should expect the date content to be changed to ISO format soon.

**Comment by sdementen** [comment]
it is not that easy as piecash should support both the current and the new schema which will require changes in the SQLAlchemy layer. 
Are you on the gnucash-dev mailing list ? I will ask how they plan to provide backward/forward compatibility when changing the date format.

**Comment by MisterY** [comment]
It turns out that both formats will be kept in the databases. Parsing should check first the ISO date and, if no value, then try the old format.
Where are these stored in piecash, btw? See #52.

**Comment by sdementen** [comment]
You can look in the sa_extra.py file

**Comment by sdementen** [comment]
But the I fail to see the benefits of changing the format ...

**Comment by MisterY** [comment]
I see line 102 but am not sure how to perform the conversion logic.

**Comment by sdementen** [comment]
are you sure the new version for splits is 4 ? previous was 1 and it looks weird to jump 3 versions at once.
btw, could you add in the gnucash_books folder of your branch sample tests of files in the new format ? for example, load the simple_sample.gnucash, resave it as simple_sample.28.gnucash and add it to the git.
I am on gnucash 2.7.0 and the versions have yet been updated but I already get the new date format. The fix for the dateformat is very easy. I push it soon

**Comment by MisterY** [comment]
Here is a dump from a new file created with 2.6.19:
```
"Gnucash"	"2061900"
"Gnucash-Resave"	"19920"
"accounts"	"1"
"billterms"	"2"
"books"	"1"
"budget_amounts"	"1"
"budgets"	"1"
"commodities"	"1"
"customers"	"2"
"employees"	"2"
"entries"	"3"
"invoices"	"3"
"jobs"	"1"
"lots"	"2"
"orders"	"1"
"prices"	"2"
"recurrences"	"2"
"schedxactions"	"1"
"slots"	"3"
"splits"	"4"
"taxtable_entries"	"3"
"taxtables"	"2"
"transactions"	"3"
"vendors"	"1"
```
I have already reverted (who knows what happens when I open this file with 2.7.3) the version numbers in my file that was modified by 2.7 so you can compare to the versions you have. For me it is quite important to have piecash access to the db so that I can use several functions and reports I'm used to. A few are still work in progress.

**Comment by sdementen** [comment]
for 2.6.19 I have it but not for 2.7.1 (or 2.7.2). Could you send the same for 2.7.N ?
and post the gnucash book also ? unless you have completely uninstalled gnucash then it is a bit cumbersome to do so...

**Comment by MisterY** [comment]
That's exactly what I did as I need a fully working system. Well, I can always play around with it later but the version numbers I committed in the branch are the ones I got after the db upgrade.
Also, note that even with 2.6.19 I get v4 for splits!

**Comment by sdementen** [comment]
the version number is updated whenever the table needs a migration so that gnucash can keep track for each table if the table need a migration or not. the v4 on splits is due to changes done some time ago.

**Comment by MisterY** [comment]
Are you sure, then, that you wanted to check the version number for Splits table?

**Comment by sdementen** [comment]
sorry, my mistake!
indeed, this is very puzzling ! in 2.6, I have v4 (as you) but in 2.7.0 I have v1 ?!?

**Comment by MisterY** [comment]
Agree. And now I have a weird mish-mash of versions since I manually downgraded a few to be able to use the db with the master branch of piecash. It's my production file. What can go wrong?! :))

**Comment by sdementen** [comment]
did you keep a copy of you book in 2.7.2?

**Comment by MisterY** [comment]
I have the last 20 manually created backups. I can compare them and give you the versions that you need, actually.

**Comment by MisterY** [comment]
Here is a snapshot from yesterday noon, when I was using 2.7.2:
```
"Gnucash"	"2061800"
"Gnucash-Resave"	"19920"
"accounts"	"1"
"billterms"	"2"
"books"	"1"
"budget_amounts"	"1"
"budgets"	"1"
"commodities"	"1"
"customers"	"2"
"employees"	"2"
"entries"	"4"
"invoices"	"4"
"jobs"	"1"
"lots"	"2"
"orders"	"1"
"prices"	"3"
"recurrences"	"2"
"schedxactions"	"1"
"slots"	"4"
"splits"	"4"
"taxtable_entries"	"3"
"taxtables"	"2"
"transactions"	"4"
"vendors"	"1"
```

**Comment by MisterY** [comment]
image

**Comment by sdementen** [comment]
looks like it 2.6.18 vs 2.6.19 (see "Gnucash" row in versions)

**Comment by MisterY** [comment]
Just added a comment below the image: "So, left is my production file, created with 2.6.18 and upgraded with 2.7.2. Right is a new file generated with 2.6.19."

**Comment by MisterY** [comment]
Here are the values from the db before 2.7.2 installation:
```
"Gnucash"	"2061800"
"Gnucash-Resave"	"19920"
"accounts"	"1"
"billterms"	"2"
"books"	"1"
"budget_amounts"	"1"
"budgets"	"1"
"commodities"	"1"
"customers"	"2"
"employees"	"2"
"entries"	"3"
"invoices"	"3"
"jobs"	"1"
"lots"	"2"
"orders"	"1"
"prices"	"2"
"recurrences"	"2"
"schedxactions"	"1"
"slots"	"3"
"splits"	"4"
"taxtable_entries"	"3"
"taxtables"	"2"
"transactions"	"3"
"vendors"	"1"
```

**Comment by sdementen** [comment]
tx! it confirms your observations indeed. 
I am left with this weird split=1 in 2.7.0 (but it is an early developer version so maybe normal to have such 'bugs')

**Comment by MisterY** [comment]
2.6.18 vs 2.6.19
image

**Comment by MisterY** [comment]
How come you're still on 2.7.0 when there's quite a few bugfixes in 2.7.1 and 2.7.2?

**Comment by sdementen** [comment]
lazy to update...

**Comment by sdementen** [comment]
using 2.7.0 for piecash dev not for real use

**Comment by MisterY** [comment]
Just pulled the latest code. Everything seems to work fine with the 2.6 db. Thanks a million!

**Comment by sdementen** [comment]
Tx to you!

**Comment by MisterY** [comment]
Holidays are here, finally, so I'll have some time to read more about unit testing in Python.

**Pull request merged**
