### PR TITLE
get_quantity()

### PR DESCRIPTION
**Pull request by MisterY**
method for getting the number of securities for commodity accounts (investments)

### CODE REVIEW

**Comment by sdementen** [comment]
Could you add some tests on this new function in https://github.com/sdementen/piecash/blob/master/tests/test_account.py ? To stress test against simple and more complex books

**Comment by MisterY** [comment]
just looking into how to that correctly

**Comment by MisterY** [comment]
Could you please help me out with the tests? I have added a sample database and the test method. I'm not sure where pytest is initialized and which book gets passed to the method, though. Should I separate this into a new class?

**Comment by sdementen** [comment]
can you already successfully launch the test locally on your machine (python setup.py test) ?

**Comment by MisterY** [comment]
Yep, I can run this specific test from the command line. How do I point it to the investment.gnucash db?

**Comment by sdementen** [comment]
piecash use pytest as a testing framework
The books are defined in test_helper as fixtures -> have a look at the book_transactions fixtures in test_helper.
You may want to create a new book for your test (like book_balance)
Then you write the new test in test_book.py like
```
class TestBook_balances(object):
    def test_balance(self, book_balance):
        assert isinstance(book_balance, Book)
        ...

```

**Comment by sdementen** [comment]
So you do not need to create explicitly the DB as you can see in https://github.com/sdementen/piecash/blob/master/tests/test_helper.py#L151 that the fixtures uses piecash itself to create dynamically the gnucash book

**Comment by MisterY** [comment]
Nice, thanks. I'll have a go at it. 
As for the database - in this case I prefer to create the file manually using GnuCash. Otherwise, I'd have to double-check that all the transactions are entered correctly. This is something to improve upon, though. It would be faster in execution if the db was in-memory but it is currently faster and safer to create all the transactions manually. I guess I can just use an existing database for this test. I've created "investment.gnucash" with a security and a couple of purchase transactions. 
Is it possible to dump some sort of text file into the database? That way all the transactions would be visible at once, so I could tell if they are correct. But still, with trading accounts, it is probably better do to it manually. As you can see, I'm undecided yet.

**Comment by sdementen** [comment]
you can put your book in the folder gnucash_books and then refer to it as for test_book.gnucash in test_helper
`file_template_full = os.path.join(book_folder, "test_book.gnucash")
`

**Comment by MisterY** [comment]
[This](https://github.com/MisterY/piecash/blob/get-quantity/gnucash_books/investment.gnucash) is the one. 
Is there any way to debug the tests?

**Comment by sdementen** [comment]
ok, can you commit the book within this PR ?

I also see problems with non-ascci characters on https://github.com/sdementen/piecash/pull/36/files#diff-b168cf480623bf447ab648b7544be5bfR133. Could you check that your IDE use UTF-8 encoding ?

**Comment by sdementen** [comment]
ho sorry, you already added it! I didn't see it at first in the commits

**Comment by MisterY** [comment]
Ah, interesting. Should probably stick to one editor only!

**Comment by sdementen** [comment]
I see indeed that some tests are failing due to the UTF-8 issue
```
E       assert 'Account<asse...ker[ï¿½oï¿½]>' == 'Account<asset:broker[ïoà]>'
E         - Account<asset:broker[ï¿½oï¿½]>
E         ?                       -- ^^^
E         + Account<asset:broker[ïoà]>
E         ?                        
```
Do the tests pass on your machine ?

**Comment by MisterY** [comment]
No, they don't pass because I have no idea what's going on. Is there a way to dump text or debug the code while the tests are running?

**Comment by sdementen** [comment]
yes, you can add "print" in the test functions.
if you use pycharm, they have even in the community edition a nice test viewer

**Comment by MisterY** [comment]
prints never show for me :(

**Comment by MisterY** [comment]
ah, I get the output, but only at the end.

**Comment by sdementen** [comment]
https://stackoverflow.com/questions/14405063/how-can-i-see-normal-print-output-created-during-pytest-run

**Comment by MisterY** [comment]
lifesaver

**Comment by MisterY** [comment]
Should I use standard piecash code to open a book? in test helper, line 233 ([link](https://github.com/MisterY/piecash/blob/e69c9b1a784dde26cb7d23221da77e2950c38365/tests/test_helper.py#L230))

**Comment by MisterY** [comment]
Phew! It passes.

**Comment by sdementen** [comment]
what is the mnemonic VEUR ?

**Comment by MisterY** [comment]
[VEUR](https://www.aex.nl/products/etfs/IE00B945VV12-XAMS)

**Comment by sdementen** [comment]
indeed, a security. haven't read carefully and I though it was a fork of the EUR currency ;-)

**Comment by MisterY** [comment]
Thanks for helping me out with the tests. Now I can separate useful scripts from tests-only.
Looking forward to actually using this code, like the security analysis, into a report.

**Comment by sdementen** [comment]
Can you commit the changes that make all test pass ? I see travis is complaining but it may not be related to your tests

**Comment by sdementen** [comment]
I still see the issues with UTF-8 on https://travis-ci.org/sdementen/piecash/jobs/303456193

**Comment by MisterY** [comment]
That one, from transactions, seems to have been there for a while. Not sure what to do here. Any recommendations?

**Comment by sdementen** [comment]
you mean it was there before the change to the line https://github.com/sdementen/piecash/pull/36/files#diff-b168cf480623bf447ab648b7544be5bfR132 ?
it seems to me that all trnasaction tests passed before ...

what is weird is that the line is marked as change while it does appear to be identical ...

**Comment by MisterY** [comment]
No, you are right. If I compare to the file in master, this new one is in ANSI. Let me redo these changes on the file.

**Comment by MisterY** [comment]
oh, man, thanks!

**Pull request merged**
