### PR TITLE
adding guid on Transaction

### PR DESCRIPTION
**Pull request by MisterY**
Adding guid on Transaction. Needed for reference, i.e. when displaying transaction details.

### CODE REVIEW

**Comment by MisterY** [comment]
Hm, this doesn't really work. I'm probably misunderstanding something about SQLAlchemy. 
But having guid exposed as a property would be really handy. I'd like to display transaction details in the web interface but am not sure how else to identify the transaction.

**Comment by MisterY** [comment]
Hm, this does not seem necessary! wohoo

**Comment by sdementen** [comment]
The models in piecash should not be changed normally as they already map exactly the table from a gnucash book. But normally you should already have some guid for transactions in the systel

**Comment by sdementen** [comment]
The models in piecash should not be changed normally as they already map exactly the table from a gnucash book. But normally you should already have some guid for transactions in the system

**Comment by MisterY** [comment]
I did not realize that guid is accepted in the .filter(). There was no guid property on Transaction entity so I tried adding it but that did not go well. :)

**Comment by sdementen** [comment]
It should inherit from a class with a guid field if I remember well

**Comment by MisterY** [comment]
You're absolutely right! I found that the retrieval of transaction by guid worked so I cancelled the pull request. 
I'm very, very happy with alchemy. Session makes it very easy to filter by parameters passed from the web input from.
Thanks a lot for mapping the GnuCash data model!

**Comment by sdementen** [comment]
Thanks to you to find/make it useful :-)

**Pull request closed without merging**
