### PR TITLE
fix for file opening with Python 3

### PR DESCRIPTION
**Pull request by MisterY**
adding CSV sample and comments

### CODE REVIEW

**Comment by MisterY** [comment]
Thank you for the quick merge!

**Comment by sdementen** [comment]
You’re welcome !
Just happened to be cheking my emails at the same time… don’t expect always the same kind of reactivity ;-)

Sébastien de MENTEN
Global Energy Management
Strategy, Communication and Corporate Social Responsibility / GEM Services
Project Lead
sebastien.dementen@engie.com<mailto:sebastien.dementen@engie.com>
T +32 2 518 67 53
M +32 478 78 94 44


engie.com<http://www.engie.com/>

ELECTRABEL S.A.
Boulevard Simón Bolívar 34,
1000 Brussels, Belgium

Please consider the environment before printing this message.

**Comment by MisterY** [comment]
He he, no worries. I intend to play around with the scripts and import. Might have further pull requests in the future, should I run into any issues. Thanks!

**Comment by sdementen** [comment]
Btw, I have some code on https://github.com/sdementen/gnucash-utilities to write reports in python (instead of scheme) integrated in the Gnucash UI if you are interested.
It is still WIP but it works !

Sébastien de MENTEN
Global Energy Management
Strategy, Communication and Corporate Social Responsibility / GEM Services
Project Lead
sebastien.dementen@engie.com<mailto:sebastien.dementen@engie.com>
T +32 2 518 67 53
M +32 478 78 94 44


engie.com<http://www.engie.com/>

ELECTRABEL S.A.
Boulevard Simón Bolívar 34,
1000 Brussels, Belgium

Please consider the environment before printing this message.

**Comment by MisterY** [comment]
Thanks for the hint! I'm finally making the first steps in migrating to GnuCash so I'll need the full toolbelt before making the jump.
As a matter of fact, I am just beginning the search on that topic! Looking for some (simple) portfolio analysis tools and/or charts.
In [MMEX](http://android.moneymanagerex.org/), I have some tools for fetching & exporting prices. Might leave it on Android for the time being (like CSV fetching & export, asset allocation, etc.) or migrate eventually. The utilities might be my missing piece for the migration.

**Pull request merged**
