### PR TITLE
export Recurrence record

### PR DESCRIPTION
**Pull request by MisterY**
I'm currently trying to get the upcoming scheduled transaction and this requires the Recurrence entity for the calculation.
Would it be correct to export the Recurrence entity or is there some other way foreseen for calculation of the next occurrence date?
Cheers

### CODE REVIEW

**Comment by sdementen** [comment]
I am not familiar at all with the recurrence table.
Maybe good time to document the class (if it gets exported). To what kind of objects can a recurrence row be linked to via the obj_guid field? Only scheduled transactions ?

**Comment by MisterY** [comment]
Yes. It describes the recurrence of a Scheduled Transactions and is used to calculate the sequence of upcoming occurrences. It is necessary to expose the class to get support for the property names in the editor.
I want to create a small window on the home page that displays the upcoming transactions in the selectable upcoming period, for example. Currently I'm going through the logic for calculation of the next occurrence date at GnuCash repo.
Let me know what and where should I describe more. I'd be happy to do that. Do you mean in docs or the code?

**Comment by MisterY** [comment]
Btw, you've already done the linking it seems. The SchedXaction has a working link in the .recurrence property.

**Comment by sdementen** [comment]
Documentation in the code could be a good start, explaining the role/interpretation of each field.
Btw, cannot the scheduled expression be simply interpreted with python ?

**Comment by MisterY** [comment]
I don't understand what exactly you're asking. Unfortunately, calculation of the next date is not so simple:
https://github.com/Gnucash/gnucash/blob/115c0bf4a4afcae4269fe4b9d1e4a73ec7762ec6/libgnucash/engine/Recurrence.c#L172

**Comment by MisterY** [comment]
Field descriptions added based on what I figured out so far.

**Pull request merged**
