### PR TITLE
Alpha Vantage implementation (In Progress)

### PR DESCRIPTION
**Pull request by rerobins**
Need a talking point.

Implements functionality of #32 

Current State:
- Code is in commodity, but not tested.
- Remove dependency on yahoo-finance
- Added direct dependency on requests library

Questions:
- Where do you want to store the alpha-vantage api key that is required?  
- How do you want to handle the use case where there is now alpha-vantage api key provided?
- Should this functionality really be in this library?  I'm of the opinion that this library should only provide access to the data structure, and a means to manipulate it if desired, but probably shouldn't manipulate it.  Applications that use this library should define how they want to manipulate the data structure, and what sources to get their data from.
- Create stock from symbol functionality kind of falls under the first question.  This function also doesn't look up the stock price from yahoo, so ?  Share currency is not defined in the alpha vantage data.

### CODE REVIEW

**Comment by sdementen** [comment]
Regarding:
- the API key: we could assume it is in a environment variable (is there some standard name for it ?) or provide it in the function that updates the quote.
- the creation of symbols, what is missing is the metadata regarding exchanges (like http://www.wikinvest.com/wiki/List_of_Stock_Exchanges) that could be used to retrieve the currency of symbols traded/quoted on some exchange
- in terms of functionality, piecash is explicitly made to manipulate gnucash books even thought it may be risky (always backup first). Upgrading quotes or adding new symbols looks like a great use case to manage valuation of portfolios. So for me, ok to have this functionality in piecash

**Comment by rerobins** [comment]
Can you provide some documentation, or point me to where it is on how to test?

I tried running `python setup.py test` and got this obtuse exception:  (Sorry for the lack of wrapping).

```
E   ValueError: Plugin already registered: /home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/pandas/conftest.pyc=<module 'pandas.conftest' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/pandas/conftest.pyc'>
E   {'cacheprovider': <module '_pytest.cacheprovider' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/cacheprovider.pyc'>, 'helpconfig': <module '_pytest.helpconfig' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/helpconfig.pyc'>, '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/pandas/conftest.pyc': <module 'pandas.conftest' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/pandas/conftest.pyc'>, 'pytestconfig': <_pytest.config.Config object at 0x7f15b3dd2b90>, 'runner': <module '_pytest.runner' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/runner.pyc'>, 'unittest': <module '_pytest.unittest' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/unittest.pyc'>, 'pastebin': <module '_pytest.pastebin' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/pastebin.pyc'>, 'skipping': <module '_pytest.skipping' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/skipping.pyc'>, 'genscript': <module '_pytest.genscript' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/genscript.pyc'>, 'session': <Session 'piecash'>, 'lfplugin': <_pytest.cacheprovider.LFPlugin instance at 0x7f15b3008bd8>, 'tmpdir': <module '_pytest.tmpdir' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/tmpdir.pyc'>, 'capture': <module '_pytest.capture' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/capture.pyc'>, 'terminalreporter': <_pytest.terminal.TerminalReporter instance at 0x7f15b300ca70>, 'assertion': <module '_pytest.assertion' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/assertion/__init__.pyc'>, 'mark': <module '_pytest.mark' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/mark.pyc'>, 'terminal': <module '_pytest.terminal' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/terminal.pyc'>, 'main': <module '_pytest.main' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/main.pyc'>, 'nose': <module '_pytest.nose' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/nose.pyc'>, '139731191914256': <_pytest.config.PytestPluginManager object at 0x7f15b40edf10>, 'python': <module '_pytest.python' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/python.pyc'>, 'recwarn': <module '_pytest.recwarn' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/recwarn.pyc'>, 'funcmanage': <_pytest.python.FixtureManager instance at 0x7f15b2dbdea8>, 'monkeypatch': <module '_pytest.monkeypatch' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/monkeypatch.pyc'>, 'resultlog': <module '_pytest.resultlog' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/resultlog.pyc'>, 'capturemanager': <_pytest.capture.CaptureManager instance at 0x7f15b327d488>, 'pytest_cov': <module 'pytest_cov.plugin' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/pytest_cov/plugin.pyc'>, 'junitxml': <module '_pytest.junitxml' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/junitxml.pyc'>, 'doctest': <module '_pytest.doctest' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/doctest.pyc'>, 'pdb': <module '_pytest.pdb' from '/home/rerobins/Repositories/MeerkatLabs/piecash/env/lib/python2.7/site-packages/_pytest/pdb.pyc'>}
```

**Comment by sdementen** [comment]
never had the issue. however, googling brought me here https://github.com/pytest-dev/pytest-django/issues/102 (symlink issues) ... does it help ?

Otherwise, have you checked your venv is activated ? can you try on python 3.6 ?

**Comment by rerobins** [comment]
I was using 2.7.  

Now using 3.6 I'm doing the following and getting the same error:

```bash
virtualenv env -p `which python3`
source env/bin/activate
pip install -r requirements-dev.txt
python setup.py test
```

**Comment by sdementen** [comment]
Not sure what is the causing the issue in your setup.
You may look at the logs of Travis CI on https://travis-ci.org/sdementen/piecash/jobs/318849735 to see if you have differences in your setup ?
Are you on a Mac?

**Comment by sdementen** [comment]
https://stackoverflow.com/questions/39926709/plugin-already-registered-error-in-pytest may be the answer. 
Essentially, install your env outside the piecash folder.

**Comment by rerobins** [comment]
That (moving virtualenv outside of directory) worked.  Is this the way I should be using virtualenv? (with virtualenvs outside of my work area)

**Comment by sdementen** [comment]
I use conda env that by default installs env in ~/.conda folder. I think mkvirtualenv also does this.
I guess then it is a good practice to not put the venv in the project folder... But I can't affirm this. Probably some googling on the topic can bring a more enlightened argument (for or against)

**Comment by sdementen** [comment]
any news on this PR ?

**Comment by rerobins** [comment]
Life has caught up with me. I did see that alphavantage library removed requirement for pandas though.

**Comment by sdementen** [comment]
This https://github.com/finance-quote/finance-quote/issues/81 could be relevant to this issue

**Comment by sdementen** [comment]
I propose to move this discussion to https://github.com/python-finance/finance-quote

**Pull request closed without merging**
