### PR TITLE
Support Python 3.12: Replace usage of 'imp' module

### LINKED ISSUE #212: Can't be installed under python 3.12: No module named 'imp'
Python 3.12 was released on October 2nd and I was curious and wanted to see if I could upgrade. One of the dependencies that failed to install was piecash with the following error:

```
Collecting piecash
  Using cached piecash-1.2.0.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/teeberg/.venvs/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/teeberg/.venvs/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/teeberg/.venvs/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fy/wpxdrm_s7z151l6_h6d7v7080000gn/T/pip-build-env-igb0_sas/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fy/wpxdrm_s7z151l6_h6d7v7080000gn/T/pip-build-env-igb0_sas/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/fy/wpxdrm_s7z151l6_h6d7v7080000gn/T/pip-build-env-igb0_sas/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/fy/wpxdrm_s7z151l6_h6d7v7080000gn/T/pip-build-env-igb0_sas/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
      ModuleNotFoundError: No module named 'imp'
      [end of output]
```

The error stacktrace refers to this import in the setup.py:

https://github.com/sdementen/piecash/blob/ec30cf469198cccf35f7ba968f889d360cfe1824/setup.py#L4

The `imp` module is imported here for this one usage:

https://github.com/sdementen/piecash/blob/ec30cf469198cccf35f7ba968f889d360cfe1824/setup.py#L70-L81

According to [the changelog](https://docs.python.org/3.12/whatsnew/3.12.html), the replacement for `imp.load_source` is a snippet like this:

```python
import importlib.util
import importlib.machinery

def load_source(modname, filename):
    loader = importlib.machinery.SourceFileLoader(modname, filename)
    spec = importlib.util.spec_from_file_location(modname, filename, loader=loader)
    module = importlib.util.module_from_spec(spec)
    # The module is always executed and not cached in sys.modules.
    # Uncomment the following line to cache the module.
    # sys.modules[module.__name__] = module
    loader.exec_module(module)
    return module
```

### PR DESCRIPTION
**Pull request by teeberg**
The `imp` module was removed in Python 3.12: https://docs.python.org/3.12/whatsnew/3.12.html#imp

Replace with equivalent code that does not use the `imp` module.

Fixes #212

### CODE REVIEW

**Comment by sdementen** [comment]
I can't fix the appveyor build to ensure the tests pass on python 3.7...3.12 for the change you submitted.
Any idea how to fix the issues in the build (they are not related to your commit)?

**Comment by teeberg** [comment]
@sdementen I see that you are removing the appveyor build in another PR: https://github.com/sdementen/piecash/pull/214/files - Do you still want to fix it?

I think the important part from that error is this:

> Could not find directory of OpenSSL installation, and this `-sys` crate cannot
> proceed without this knowledge. If OpenSSL is installed and this crate had
> trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
> compilation process.

I'm not fully sure what the right values for `OPENSSL_DIR` are, but I found some other build here that sets those: https://github.com/h2o/picotls/blob/master/appveyor.yml - Maybe we could take the same ones?

**Comment by sdementen** [comment]
indeed, I finally removed the appveyor things. Tests are only running on
linux through the github actions. Would be nice to add tests on windows
through the github actions...

**Comment by sdementen** [comment]
can you merge the changes I've done in master to your branch ? it will also rerun the build to see if it passes the tests

**Comment by teeberg** [comment]
@sdementen Already did that! :) Github is still expecting the appveyor status checks, though.

image

Did you already change those in the repo settings?

**Comment by sdementen** [comment]
I have removed the piecash project on the appveyor website ...

**Comment by sdementen** [comment]
I will force the merge anyway as all the tests pass on linux

**Comment by teeberg** [comment]
According to this stackoverflow post, the checks should be configurable here:

```
Settings
  Branches
    Branch protection rules  
      Edit (next to your desired branch, e.g. 'master')  
        Rule settings  
          Require status checks to pass before merging
            Require branches to be up to date before merging 
              < Uncheck any statuses you want to disable! >
```

**Comment by teeberg** [comment]
@sdementen Any chance of getting this released to PyPi? :)

**Comment by sdementen** [comment]
Yes, I should be able to do a new release soon

**Pull request merged**
