### PR TITLE
reading the default currency from preferences (on Windows)

### PR DESCRIPTION
**Pull request by MisterY**
I'm not sure how to test this well. I'd appreciate if you could confirm that this works as intended. :)

### CODE REVIEW

**Comment by MisterY** [comment]
I'll have to check this again probably.

**Comment by sdementen** [comment]
@MisterY Could you have a look at the changes I have done re your proposal ?
but also could you test it ? I can't test it locally as I do not have the keys in my registry ... why? maybe because I am on 2.7.1

**Comment by MisterY** [comment]
Sure! 
Are you using 2.7.1 on your production book file?
Does this mean that with 2.8.0 the default currency will not be stored in GPreferences (or whatever the name is)?

**Comment by sdementen** [comment]
maybe indeed...

**Comment by MisterY** [comment]
Syntax error in book.py line 162

**Comment by sdementen** [comment]
I have fixed it via https://github.com/sdementen/piecash/pull/34/commits/0c6d1d04b5d183136b4c18456a086279751b75ce

**Comment by MisterY** [comment]
The test shows me EUR, as it should. I guess it's a pass. :)

**Comment by MisterY** [comment]
Tried with IRR. Works as soon as the setting is changed in the Preferences.

**Comment by MisterY** [comment]
I think I'll follow your example and switch to 2.7.2. I've tried it earlier and it acts much faster on my work PC.

**Comment by sdementen** [comment]
I think a better way to test would be to mock the winreg package, maybe with https://pypi.python.org/pypi/pytest-mock (never done that before!)

**Comment by sdementen** [comment]
Hello @mistery, I have fixed the default currency property of a book to return the currency of the ROOT account.
The default currency that needs the locale or the registry is to get the currency when creating a new book.
As currently, the user can provide the currency at book creation, I think there is no much use cases where we would like to guess the latter default currency.
Ok to close this PR without merging?

**Comment by MisterY** [comment]
Hi! Can you confirm that changing the default currency in the preferences changes the currency of the root account? Cheers

**Comment by sdementen** [comment]
you mean in Gnucash (not piecash), correct ?
reading jralls comment "I think that the currency offered on the accounts page is the currency of the ROOT account. That’s set when you create a new book with File>New and its default is the default currency in Preferences. Once it’s set for a book it can’t be changed in the GUI." ==> it appears the default currency from the preferences is the currency used to report on the front page.
When creating new accounts in your book, gnucash uses not this ROOT account default currency but the one defined in the preferences ("Use this currency as the default for new accounts").

in piecash, seen it is a programmatic access, I do not think using any default currency when creating an account makes really sense. If someone wants to create a new account in the same currency as the ROOT account, he/she can uses the book.default_currency.

**Comment by MisterY** [comment]
It turned out that his guess was not correct. But this is irrelevant here. The default currency is a setting in preferences and is used as the default for any new account. In GnuCash. It can be changed in the GUI. I would assume this is stored in the registry on Windows and does not change the currency of the root account but should be checked.

**Comment by sdementen** [comment]
there is 2 different things:
1)  for new account, you are right, you can change the "default currency for new accounts" in the preferences (and john did not say the opposite)
2) for a book, the summary of your book given in the bottom bar of Gnucash (with "total assets", etc) is given in a the ROOT account currency that can only be defined once at creation of a book (second screen in the wizard) and cannot be changed afterwards in the GUI. However, in the 2nd screen of the wizard for book creation, they ask to choose "the default currency to use when creating new accounts" which is completely misleading ==> that's a documentation/UI bug in gnucash

**Comment by MisterY** [comment]
Yes, it seems that "the default currency" and its effects should be well defined first.

**Comment by MisterY** [comment]
With this explanation, I see not much point in having or using the default currency setting. Any custom reports or functions should use their own setting for the currency of the result. So, yes, this can be closed as my assumptions about the default currency behaviour are wrong in case of GnuCash.

**Pull request closed without merging**
