### PR TITLE
Support for GnuCash 3.7 database schema

### PR DESCRIPTION
**Pull request by pboettch**
Quick fix for #126 - code shamelessly stolen from @OliverEvans96

### CODE REVIEW

**Comment by andygoblins** [comment]
This won't work for everybody--my database is currently version 3000006.

It looks like gnucash sets this version based on major/minor number ([gnc_prefs_get_long_version](https://github.com/Gnucash/gnucash/blob/maint/libgnucash/core-utils/gnc-prefs.c)), so technically people could have 3000007 too.

**Comment by NigelCleland** [comment]
Agreed with @andygoblins, I currently have version 3000007 following a fresh install today. Unsure on the best way to handle this going forward if GNUCash will be updating their version number constantly. 

It appears as though Gnucash-Resave didn't change from 2.6 -> 3.0 either which had changes

**Comment by larslr** [comment]
Looking further down the code, it seems like any version difference for keys containing "Gnucash" is ignored anyway, so both Gnucash and Gnucash-Resave can be whatever. This is likely just as well, since Gnucash is modified without any of the table versions being touched, and Gnucash-Resave has remained constant through several table changes.

As far as I can tell, this patch should work, with the caveat that any version 3.0->3.6 will be recognized as 3.0 and any future 3.8+ with no table changes will be identified as 3.7. I don't see that as a big problem.

**Comment by peterb12** [comment]
Will this be merged in any time soon, or is additional analysis needed? Not complaining, just curious about the timeline.

**Comment by almereyda** [comment]
I have cloned this branch and can confirm that it works together with https://github.com/henriquebastos/gnucash-to-beancount/issues/14 when cloned from the PR source and installed with `pip3 install --user .` within the repository.

**Pull request merged**
