### PR TITLE
example for reading a currency with details and historical prices

### PR DESCRIPTION
**Pull request by MisterY**
Another fairly simple example that focuses only on currencies and historical prices.
Might be useful for fetching data for an exchange rate graph.
The main benefit is for beginners.

### CODE REVIEW

**Comment by sdementen** [comment]
nice to have simple examples for starters!
however, why do you use directly the SA session instead of accessing the commodities as described in http://piecash.readthedocs.io/en/latest/tutorial/index_existing.html#commodities-and-prices or in http://piecash.readthedocs.io/en/latest/tutorial/index_existing.html#other-objects ?

**Comment by MisterY** [comment]
Heh, probably because I did not read that far! :) 
SQLAlchemy queries seemed to satisfy all my needs up to that point (Commodities and Prices).

So, are you saying that using `book.get(Commodity, ...` is preferable to using session? What are the practical implications? Are there any benefits to using one over the other? 
I will adjust the sample with the best-practice and would like to know more. The answer to this is not obvious from the doc. Thanks!
Cheers

**Comment by sdementen** [comment]
Not specially preferable. It requires just no knowledge of SA which for beginners may better.

Now, related to commodities, it could be interesting to use http://alpha-vantage.readthedocs.io/en/latest/ for uploading quotes (seen the stop of the yahoo finance interface) as it is currently a discussion topic on the gnucash mailing lists.

**Comment by MisterY** [comment]
That seems to be the pain point for many these days, I guess.
What I did for Money Manager Ex, as the quick solution, was to implement Fixer for currency exchange rates (not too many available, but free). I also already had a Morningstar parsing for stocks and funds. That works quite well and has a wide range of securities available. 
Now, I'd hope to translate these into Python or Perl, whichever works. At the moment, I can't update prices from GnuCash on Windows, whichever source I select. Not sure what exactly is going on there, so I'm leaning towards the scrips that I can inspect.

I was thinking to adjust this script to dump all the used currencies into a file which can be used as a source for a script that downloads the prices from the desired source. Do you know if there is a way to get only the currencies that are in use (for accounts, for example)?
If not, the list of currencies can be maintained manually. That doesn't change often, anyway.

**Comment by sdementen** [comment]
I think the commodities in the book are only the ones used. Have a check!
You can also check the accounts or transactions field of a commodity to set if it is referred somewhere (http://piecash.readthedocs.io/en/latest/api/piecash.core.commodity.html#piecash.core.commodity.Commodity.accounts)

I think a script to update the prices for commodities/currencies in use through http://alpha-vantage.readthedocs.io/ would be very simple to write.

Sébastien de MENTEN
Global Energy Management
Strategy, Communication and Corporate Social Responsibility / GEM Services
Project Lead
sebastien.dementen@engie.com<mailto:sebastien.dementen@engie.com>
T +32 2 518 67 53
M +32 478 78 94 44


engie.com<http://www.engie.com/>

ELECTRABEL S.A.
Boulevard Simón Bolívar 34,
1000 Brussels, Belgium

Please consider the environment before printing this message.

**Comment by MisterY** [comment]
You're right about the commodities - only the ones used are shown. That's perfect!
I can't figure out how to get currencies only through get(**kwargs). What would be the correct arguments?
'currencies = book.get(Commodity, namespace="CURRENCY")` doesn't do it so I left the code using session.

**Comment by sdementen** [comment]
```
# to get a specific element of these lists
EUR = book.commodities(namespace="CURRENCY", mnemonic="EUR")
```
(see http://piecash.readthedocs.io/en/latest/api/piecash.core.book.html)

**Comment by MisterY** [comment]
Right, I'm using that to fetch the requested (single) currency. Are there any arguments to fetch only currencies?
I mean, specifically this part:
```
print("All currencies used in the book:")
#currencies = book.get(Commodity, namespace="CURRENCY")
currencies = session.query(Commodity).filter(Commodity.namespace == "CURRENCY").all()
```

**Comment by sdementen** [comment]
you can see the SA details here for instance https://github.com/sdementen/piecash/blob/master/piecash/core/book.py#L357

**Comment by sdementen** [comment]
Does the following work ? I think it should but not sure 100%
```
for cur in book.currencies:
   do something with cur

```

**Comment by MisterY** [comment]
👍

**Comment by MisterY** [comment]
You did a great job here. Hope some kind of portfolio analysis can be done on top. Now, when I have some time, I need to learn more about generating charts and html reports in Python.

**Comment by sdementen** [comment]
for portfolio analysis/reporting, have a look at https://github.com/sdementen/piecash/blob/master/piecash/core/book.py#L357 and http://piecash.readthedocs.io/en/latest/api/piecash.core.book.html#piecash.core.book.Book.splits_df
it is some way of extracting the data from a book on a pandas DataFrame format.
Once you have it in pandas, it opens the door to the fantastic plotly (https://plot.ly/python/)

**Comment by sdementen** [comment]
btw, the docs of piecash are not very well structured so it may be complex to find the right page. If you want to work on this, you're most welcome ;-)

**Comment by MisterY** [comment]
Thanks for these links. It's a treasure-trove. :)
As for the docs, I think they're fine. Just that people might not be up for reading. ;) What would be great (for me, perhaps) is to insert the relevant links directly into the source code and organize the examples well. I might do that with this sample and keep using the same principle later.

**Comment by sdementen** [comment]
and for opening books, it is better to use the context manager
`book = piecash.open_book(filename, open_if_lock=True)`
becomes
```
with piecash.open_book(filename, open_if_lock=True) as book:
    # rest of the code
```
as this will "close" properly the book (see http://piecash.readthedocs.io/en/latest/tutorial/examples.html#extract-split-information-as-pandas-dataframe)

**Comment by MisterY** [comment]
That's about it for this example. I'm gonna try some charting with plot.ly.

**Pull request merged**
